language: android
sudo: false
jdk:
  - oraclejdk8
android:
    components:
        - platform-tools
        - tools
        - build-tools-26.0.2
        - android-27
        - extra-android-m2repository
script:
    - cd BlinkIDSample
    - ./gradlew clean :BlinkIDSample-BlinkIDSample:assembleRelease
    - ./gradlew clean :BlinkIDSampleCustomSegmentScan:assembleRelease
    - ./gradlew clean :BlinkIDSampleCustomUI:assembleRelease
    - ./gradlew clean :BlinkIDDetectorSample:assembleRelease
    - ./gradlew clean :BlinkIDDirectApiSample:assembleRelease
    - ./gradlew clean :BlinkIDRandomScanSample:assembleRelease
    - ./gradlew clean :BlinkIDImageListenerSample:assembleRelease
    - ./gradlew clean :BlinkIDCustomCombinedSample:assembleRelease
